stages:
  - build_and_upload

variables:
  VERSION: ${CI_COMMIT_TAG}
  BINARY_NAME: "IMGT_StatAssembly"  # Define your binary name
  OS: ${CI_RUNNER_TAGS}  # Assuming you use runner tags to identify the OS
  FILE_EXTENSION: "tar.gz"  # Default file extension, can be overridden in script

build-and-upload:
  stage: build_and_upload
  script:
    - echo "VERSION=${VERSION}" >> .env
    - rustup update stable
    - cargo build --verbose --release --target ${TARGET}
    - mkdir "${BINARY_NAME}-${VERSION}-${TARGET}"
    - mv "target/${TARGET}/release/${BINARY_NAME}" "${BINARY_NAME}-${VERSION}-${TARGET}"
    - if [[ "${OS}" == "windows-latest" ]]; then
        7z a "${BINARY_NAME}-${VERSION}-${TARGET}.zip" "${BINARY_NAME}-${VERSION}-${TARGET}"
        FILE_EXTENSION="zip"
      else
        tar -czf "${BINARY_NAME}-${VERSION}-${TARGET}.tar.gz" "${BINARY_NAME}-${VERSION}-${TARGET}"
      fi
    - echo "ASSET=${BINARY_NAME}-${VERSION}-${TARGET}.${FILE_EXTENSION}" >> .env
  artifacts:
    paths:
      - "${BINARY_NAME}-${VERSION}-${TARGET}.${FILE_EXTENSION}"
    expire_in: 1 week
  only:
    - tags
  parallel:
    matrix:
      - TARGET: "x86_64-unknown-linux-gnu"
      - TARGET: "x86_64-apple-darwin"
      - TARGET: "x86_64-pc-windows-gnu"