name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Software version'
        required: true
      prerelease:
        description: 'Pre-release?'
        required: false
        default: false
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          generate_notes: true
          overwrite: true

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          if: runner.os == 'Linux'
          run: |
              sudo apt-get update
              sudo apt-get -y install \
                libfontconfig1-dev \
                libharfbuzz-dev \
                libtiff-dev \
                libconfig++-dev \
                libconfig-dev
        - name: Setup OpenSSL
          if: runner.os == 'Windows'
          shell: powershell
          run: |
              choco install openssl.light
              echo "OPENSSL_DIR=C:\Program Files\OpenSSL-Win64" >> $env:GITHUB_ENV
              echo "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL-Win64\lib" >> $env:GITHUB_ENV
              echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL-Win64\include" >> $env:GITHUB_ENV
              echo "OPENSSL_NO_VENDOR=1" >> $env:GITHUB_ENV
              echo "RUSTFLAGS=-Ctarget-feature=+crt-static" >> $env:GITHUB_ENV
              echo "C:\Program Files\OpenSSL-Win64\bin" >> $env:GITHUB_PATH
        - name: Setup OpenSSL
          if: runner.os == 'macOS'
          run: |
              brew install openssl@3
              echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
        - uses: taiki-e/upload-rust-binary-action@v1
          with:
            bin: IMGT_StatAssembly
            include: LICENSE,README.md
            target: ${{ matrix.target }}
            archive: $bin-$tag-$target
            tar: unix
            zip: windows
            token: ${{ secrets.GITHUB_TOKEN }}
