name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Software version'
        required: true
      prerelease:
        description: 'Pre-release?'
        required: false
        default: false
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          generate_notes: true
          overwrite: true

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup OpenSSL
      if: runner.os == 'windows'
      shell: powershell
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        vcpkg install openssl:x64-windows-static-md
        vcpkg integrate install
        set VCPKGRS_DYNAMIC=1
        $env:OPENSSL_DIR:"<vcpkg>\installed\x64-windows-static"
    - name: Install dependencies
      if: runner.os == 'linux'
      run: |
          sudo apt-get update
          sudo apt-get -y install \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libtiff-dev \
            libconfig++-dev \
            libconfig-dev
    - uses: actions/checkout@v4
    - uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: IMGT_StatAssembly
        target: ${{ matrix.target }}
        tar: unix
        zip: windows
        token: ${{ secrets.GITHUB_TOKEN }}
